// <auto-generated />
namespace T3DiarsClinica.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2medc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2medc));
        
        string IMigrationMetadata.Id
        {
            get { return "201711151908410_2medc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
